language: node_js
node_js:
  - '12'
  - '10'
before_install:
  - yarn global add greenkeeper-lockfile@1
install: yarn --ignore-engines
before_script: greenkeeper-lockfile-update
script:
  - yarn lint && yarn typecheck && yarn test
after_script: greenkeeper-lockfile-upload
cache:
  yarn: true
  directories:
    - node_modules
