language: node_js
node_js:
  - '10'
  - '8'
before_install:
  - yarn global add greenkeeper-lockfile@1
install: yarn --ignore-engines
before_script: greenkeeper-lockfile-update
script:
  - yarn lint && yarn flow && yarn test
after_script: greenkeeper-lockfile-upload
jobs:
  include:
    - stage: release
      node_js: '8'
      os: linux
cache:
  yarn: true
  directories:
    - node_modules
